---
instances:
- https://rss.shab.fun/
- https://vercel.getrss2021.xyz/
- https://rsshub.rssforever.com/
- http://getrss2021.xyz:1200/
- https://rsshub.app/
routes:
- title: 沉冰浮水 的追番列表
  path: bilibili/user/bangumi/44744006
# baseUrl: https://raw.githubusercontent.com/wdssmq/proxy_rsshub/main # The Base Url Of xml folder

